# Generated by Django 5.2.4 on 2025-08-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('phone', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('phone', models.CharField()),
                ('comment', models.CharField()),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.master')),
            ],
        ),
    ]
